In [2]:
import numpy as np

# Problem 1

Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

Input
> Array1: [ 0 10 20 40 60]
Array2: [0, 40]

Output
> Compare each element of array1 and array2
Output: [ True False False True False]

In [ ]:
# your code goes here

In [2]:
import numpy as np
def existence_check(a1, a2):
    print(f'Array1: {a1}')
    print(f'Array2: {a2}')
    return np.in1d(a1, a2) # isin

array1 = np.array([ 0, 10, 20, 40, 60])
array2 = np.array([0, 40])
print(f'output: {existence_check(array1, array2)}')

Array1: [ 0 10 20 40 60]
Array2: [ 0 40]
output: [ True False False  True False]


***********

# Problem 2

Write a NumPy program to get the unique elements of an array

input
>Original array:
[10 10 20 20 30 30]

Output
> Unique elements of the above array:
[10 20 30]

Input
> Original array:
[[1 1]
[2 3]]

Output
>Unique elements of the above array:
[1 2 3]

In [ ]:
# your code goes here

In [3]:
def get_unique(original_array):
    print(f'Original array:\n{original_array}')
    return np.unique(original_array)

array = np.array([[1,1], [2,3]])
print(f'Unique elements of the above array:\n{get_unique(array)}')

Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


***

# Problem 3

Write a NumPy program to sort an along the first, last axis of an array.

Input

Original array:
> [[4 6]
> [2 1]]

Output
> Sort along the first axis:
>
> [[2 1]
>
> [4 6]]


> Sort along the last axis:
>
> [[4 6]
>
> [1 2]]

In [ ]:
# your code goes here

In [4]:
array = np.array([[4, 6], 
                  [2, 1]])

last = np.sort(np.sort(array, axis = 0), axis = 1)
last

array([[1, 2],
       [4, 6]])

In [4]:
def arr_sort(array):
    print(f'Original array:\n{array}')
    
    #along first axis (column sort)
    first = np.sort(array, axis = 0) # sorting the original array
    
    #along last axis (row sort)
    last = np.sort(array, axis = 1) # sorting the original array
    
    return first, last

array = np.array([[4, 6], 
                  [2, 1]])

first , last = arr_sort(array)
print(f'Sort along the first axis:\n {first} \n\n sort along the last axis:\n {last}')

Original array:
[[4 6]
 [2 1]]
Sort along the first axis:
 [[2 1]
 [4 6]] 

 sort along the last axis:
 [[4 6]
 [1 2]]


# Problem 4

Write a NumPy program to count the occurrence of a specified item in a given NumPy array.

Input
> Original array:
>
> [10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]
> 
> item to count = 20

Output
>7

In [ ]:
# your code goes here

In [15]:
array = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
np.count_nonzero(array==20)

7

In [6]:
def item_count(array, item_to_count):
    print(f'Original array:\n{array}\n')
    print(f'item to count:\n{item_to_count}\n')
    count = np.sum(array == item_to_count)
    return count

array = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
print(item_count(array, 20))

Original array:
[10 20 20 20 20  0 20 30 30 30  0  0 20 20  0]

item to count:
20

7


## <font color=red> Note </font>

np.sum(array == item_to_count)

is using the comparison operator
it will return a boolean list like this: [False, True, True, True, True, False, ...etc.] 

Then it will sum the boolean results Note that True = 1, False = 0.

So, the sum will be the occurnce of the value

***

# Problem 5

Write a NumPy program to count the occurrence of a each item in a given NumPy array.

Input
> Original array:
>
> [10 20 20 20 20 0 20 30 30 30 0 0 20 20 0]

Output
>[4,1,7,3]

In [13]:
array = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])

np.unique(array, return_counts = True)[1]

array([4, 1, 7, 3])

In [14]:
array = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
np.bincount(array)

array([4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 3])

In [15]:
array = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0]) # 0, 10, 20, 30
bc_array = np.bincount(array) #0, 1, 3, 4, 7
np.unique(bc_array)

array([0, 1, 3, 4, 7])

In [27]:
array = np.array([10, 20, 20, 20, 20, 20,0, 30, 30, 30, 0, 0, 20, 20, 0]) # 0, 10, 20, 30

sort_arr = np.sort(array)
print(sort_arr)
c = np.bincount(sort_arr)
print(c)

output = list()
for i in np.unique(array): # 0, 10, 20, 30
    output.append(c[i])
print(output)

[ 0  0  0  0 10 20 20 20 20 20 20 20 30 30 30]
[4 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 0 0 0 0 3]
[np.int64(4), np.int64(1), np.int64(7), np.int64(3)]


In [31]:
input = [10, 20, 20, 20, 20, 20,0, 30, 30, 30, 0, 0, 20, 20, 0]
output = [4,0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]
         [0,1, 2, 3, 4, 5, 6, 7, 8, 9,10, 11,12,13,14                                              30]
# n = [4,0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]

# n[20]

7

In [ ]:
# Your code goes here

In [11]:
def item_count(array):
    print(f'Original array:\n{array}\n')
    c = np.bincount(np.sort(array))
    output = list()
    for i in np.unique(array):
        output.append(c[i])
    return output

array = np.array([10, 20, 20, 20, 20, 0, 20, 30, 30, 30, 0, 0, 20, 20, 0])
print(item_count(array))

Original array:
[10 20 20 20 20  0 20 30 30 30  0  0 20 20  0]

[4, 1, 7, 3]


****

# Problem 6

Write a NumPy program to remove nan values from a given array.

Input
> Original array:
>
> [200. 300. nan nan nan 700.]

Output
> After removing nan values:
> [200. 300. 700.]

In [37]:
array = np.array([200., 300., np.nan, np.nan, np.nan, 700.])
print(np.isnan(array))
array[~np.isnan(array)]  # inverse or not is nan

[False False  True  True  True False]


array([200., 300., 700.])

In [34]:
array = np.array([200., 300., np.nan, np.nan, np.nan, 700.])

[x for x in array if np.isfinite(x)]

[np.float64(200.0), np.float64(300.0), np.float64(700.0)]

In [38]:
array = np.array([200., 300., np.nan, np.nan, np.nan, 700.])
print(np.isfinite(array))
array[np.isfinite(array)]

[ True  True False False False  True]


array([200., 300., 700.])

In [39]:
array = np.array([200., 300., np.nan, np.nan, np.nan, 700.])
array[np.logical_not(np.isnan(array))]

array([200., 300., 700.])

In [12]:
def nan_removal(array):
    print(f'Original array:\n{array}')
    return array[np.logical_not(np.isnan(array))]

array = np.array([200., 300., np.nan, np.nan, np.nan, 700.])
print(f'After removing nan values:\n{nan_removal(array)}')

Original array:
[200. 300.  nan  nan  nan 700.]
After removing nan values:
[200. 300. 700.]


***

# Problem 7

Write a NumPy program to calculate percentiles for a sequence or single-dimensional NumPy array.

eample of an array:
[1, 2, 3, 4, 5, 6]

Input
>50th percentile (median):
> 3.0


> 40th percentile:
> 2.6


> 90th percentile:
> 4.6

In [ ]:
# Your code goes here

In [45]:
def get_percentile(array):
    print(f'50th percentile (median):\n{np.percentile(array, 50)}')
    print(f'40th percentile (median):\n{np.percentile(array, 40)}')
    print(f'90th percentile (median):\n{np.percentile(array, 90)}')

#array = np.arange(1, 11)
#array = np.arange(0,5)
array = np.arange(1,7)
get_percentile(array)

50th percentile (median):
3.5
40th percentile (median):
3.0
90th percentile (median):
5.5


***

# Problem 8

Write a NumPy program to find indices of elements equal to zero in a NumPy array.


Input
> Original array:
> [1 0 2 0 3 0 4 5 6 7 8]

Output
> Indices of elements equal to zero of the said array:
> [1 3 5]

In [20]:
# Your code goes here

In [17]:
def is_zero(array):
    print(f'Original array:\n{array}')
    print(f'Indices of elements equal to zero of the said array:\n{np.where(array == 0)[0]}')#using [0] because it return tuble

array = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])
is_zero(array)

Original array:
[1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal to zero of the said array:
[1 3 5]


***

# Problem 9

Write a NumPy program to round elements of the array to the nearest integer, and then calculate the abslute value element wise.


Input
> Original array:
> [-0.7 -1.5 -1.7 0.3 1.5 1.8 2. ]

Output
> Round elements of the array to the nearest integer:
> [1. 2. 2. 0. 2. 2. 2.]

In [ ]:
# your code goes here

In [8]:
def round_get_absolute(array):
    print(f'Original array:\n{array}')
    
    #np.rint: already handles the decimals
    print(f'Round elements of the array to the nearest integer:\n{np.absolute(np.rint(array))}')
    print('or')
    #np.round: also can be used but we have to handle a sitaution where the number has two decimals "5.62" (decimals = 0)
    print(f'Round elements of the array to the nearest integer:\n{np.absolute(np.round(array, decimals = 0))}')
    
array = np.array([-0.7, -1.5, -1.7, 0.3, 1.5, 1.8, 2.])
round_get_absolute(array)

Original array:
[-0.7 -1.5 -1.7  0.3  1.5  1.8  2. ]
Round elements of the array to the nearest integer:
[1. 2. 2. 0. 2. 2. 2.]
or
Round elements of the array to the nearest integer:
[1. 2. 2. 0. 2. 2. 2.]


#### np.rint is specifically designed for rounding to the nearest integer.

#### np.round is more general and allows for rounding to a specified number of decimal places.

# Problem 10

Write a NumPy program to calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to a given array.

Input
> Original array:
> [1 3 5 7 0]

Output
>Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
> [ 0 0 2 2 2 -7 200]

Note: difference between neighboring elements means: out[i] = a[i+1]-a[i]

In [ ]:
#your code goes here

In [ ]:
np.r_([0,0,np.diff(array), 200])

In [22]:
def subtract_and_insert(array):
    print(f'Original array:\n{array}')
    
    #np.insert(array_to_save_into, index, what_to_save, axis)
    diff_with_zero = np.insert(np.diff(array), 0, [0, 0], axis = 0)
    final_array = np.insert(diff_with_zero, len(diff_with_zero), 200, axis = 0) 
    print(f'Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:\n{final_array}')
    
array = np.array([1, 3, 5, 7, 0])
subtract_and_insert(array)

Original array:
[1 3 5 7 0]
Difference between neighboring elements, element-wise, and prepend [0, 0] and append[200] to the said array:
[  0   0   2   2   2  -7 200]


In [ ]:
# solution using for loops
array = np.array([1, 3, 5, 7, 0])

for x in range(1, len(array)):
    print(array[x] - array[x-1])

print()

for x in range(len(array)-1):
    print(array[x+1] - array[x])

# TODO:
# Contiue with prepend and append

# Problem 11

Write a NumPy program to get the indices of the sorted elements of a given array.

Input
> Original array:
> [1023 5202 6230 1671 1682 5241 4532]

Output
>Indices of the sorted elements of a given array:
>[0 3 4 6 1 5 2]

In [ ]:
# your code goes here

In [23]:
def get_indices(array):
    print(f'Original array:\n{array}')
    print(f'Indices of the sorted elements of a given array:\n{np.argsort(array)}')
    
array = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
get_indices(array)

Original array:
[1023 5202 6230 1671 1682 5241 4532]
Indices of the sorted elements of a given array:
[0 3 4 6 1 5 2]


***

***

In [6]:
import numpy as np
array = np.array([70, 50, 20, 30, -11, 60, 50, 40])

print(np.partition(array, 4))
print(np.partition(array, 1))
print(np.partition(array, 2))
print(np.partition(array, 3))

[-11  20  30  40  50  50  60  70]
[-11  20  30  40  50  50  60  70]
[-11  20  30  40  50  50  60  70]
[-11  20  30  40  50  50  60  70]


# Problem 12

Compute the euclidean distance between two arrays a and b.

Input:
> [1,2,3,4,5]
  
> [4,5,6,7,8]

Output
>Euclidean distance is: 6.7082

In [ ]:
# your code goes here

In [26]:
def euclidean_distance_np(a1, a2):
    """Calculating euclidean distance using numpy linear algebra"""
    print(f'input:\n{a1}\n{a2}')
    print(f'Euclidean distance is: {np.round(np.linalg.norm(a1 - a2), decimals = 4)}')
    
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
euclidean_distance_np(a, b)

input:
[1 2 3 4 5]
[4 5 6 7 8]
Euclidean distance is: 6.7082


***

# Problem 13

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
>array([1, 3, 7, 1, 2, 6, 0, 1])

Output:
>array( [2, 5])

where, 2 and 5 are the positions of peak values 7 and 6.

In [ ]:
# your code goes here

In [28]:
from scipy.signal import find_peaks
def get_peaks_indices(array):
    ind = find_peaks(array)
    print(ind[0])


array = np.array([1, 3, 7, 1, 2, 6, 0, 1])
get_peaks_indices(array)

[2 5]


***

# Problem 14

Find the index of nth repetition of number i .

Inputs
> array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
> 
> n = 5 (from user)
> 
> i = 1 (from user)

Output
>8

In [ ]:
# your code goes here

In [30]:
def get_ind(array, n, i):
    ind = np.argwhere(array == i)[n-1]
    print(f'output:\n{ind[0]}')
    
array = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = int(input())
i = int(input())
get_ind(array, n, i)

5
1
output:
8
